### PR TITLE
Change the local_format in Taiwan

### PR DESCRIPTION
**Pull request by ymhuang0808**
Change the `local_format` in Taiwan 🇹🇼 for the conventional address format.

### CODE REVIEW

**Comment by ymhuang0808** [comment]
In TravsCI, HHVM environment cannot build.

**Comment by yaazkal** [comment]
Hi, I think that is not the file to be changed, if you want the mantainers to consider this, they will ask you to add the custom format to `get_address_format_customizations()` function located in [resources/library_customizations.php](https://github.com/commerceguys/addressing/blob/master/resources/library_customizations.php) file.

I need to clarify that I'm not a mantainer of the project but seems that AddressFormatRepository.php is overrided after the generate.php script is ran.

Regards.

**Comment by bojanz** [comment]
This PR is doing the wrong thing, it's not the TW format that's wrong, it's our code that swaps the two address lines when the direction of the fields is reversed (major-to-minor). The fix would be somewhere in generate.php

**Comment by ymhuang0808** [comment]
Thanks @yaazkal 

Hmm, I added the revised format in `get_address_format_customizations()` and executed the scripts/generate.php which produced scripts/address_formats.php. It seems like that I should copy the result to AddressFormatRepository.php. 

According to @bojanz , should generate.php override the address format into AddressFormatRepository.php directly?

**Comment by bojanz** [comment]
Fixed in 35064bc6ed1e81383d2fc52e826c1cade3b07c96.

**Pull request closed without merging**
