### PR TITLE
Feature/php7.3 language features and typehints

### PR DESCRIPTION
**Pull request by Chris53897**
See https://github.com/commerceguys/addressing/pull/166

* Add php 7.3 language features
* Add typehints
* Remove some docBlocks that do not add values
* I did change same Types: Allow null values to sweet tests.
  Correct some wrong types.

### CODE REVIEW

**Comment by bojanz** [comment]
Thank you for opening this PR. I will try to review it in the next day or two.

**Comment by bojanz** [comment]
Sorry for the delay. Now merged. Thanks!

**Comment by mlocati** [comment]
This is a breaking change and shoundl't have been published in the 1.x releases series: it's breaking our code!

We have this error now:
```
Declaration of
Our\Address\Formatter::buildView(CommerceGuys\Addressing\AddressInterface $address, CommerceGuys\Addressing\AddressFormat\AddressFormat $addressFormat, array $options)
must be compatible with
CommerceGuys\Addressing\Formatter\DefaultFormatter::buildView(CommerceGuys\Addressing\AddressInterface $address, CommerceGuys\Addressing\AddressFormat\AddressFormat $addressFormat, array $options): array
```

**Comment by Chris53897** [comment]
Yes, a major version should have been better. I should have mentioned this in my text. One solution for you is to just add array as return type or add a constraint in your composer.json to use a older version.

I am not sure what is the best solution for this repo. Make a new 2.0 version and release a minor version with some reverted changes? But this could lead to problems for other users who has already adapted there code.

**Comment by bojanz** [comment]
If we revert the break we'll just cause another break for consumers who already adapted (like Drupal). Breaks like this can only be resolved if discovered quickly enough.

Sorry about that. I won't be making any major changes to 1.x in the future.

**Comment by mlocati** [comment]
> If we revert the break we'll just cause another break

Nope.

Return values can be only "restricted" by interface implementations and by overridden methods.

For example, let's assume the following code:

```php
interface InterfaceName
{
	// whatever
}

class CommerceguyClass
{
	public function f()
	{
	}
}

class OurExtendedClass extends CommerceguyClass
{
	public function f()
	{
	}
}
```

These two methods don't have a return type declaration, so "any" return value is allowed.

If we change the `f()` implementation of the `CommerceguyClass` class by adding a return type (like it has been done in this PR), we have a breaking change ([example](https://3v4l.org/dWAOU)), since the method being overridden has a return type stricter than the overriding method.

If instead the `f()` implementation of the `OurExtendedClass ` class returns something stricter, everything's ok ([example](https://3v4l.org/Air6a)).

**Comment by mlocati** [comment]
BTW not everything can be reverted: I've seen that also the method arguments have been added a type, and this can't be removed (method arguments in extended classes can only be made stricter in extended classes).

So, the only solution is to keep the things like they are now, and we have to add `"commerceguys/addressing": "^1.0 <1.4"` in our composer requirements.

**Pull request merged**
