### PR TITLE
replace deprecated code in AddressType.php

### PR DESCRIPTION
**Pull request by dnagirl**
As described in https://github.com/symfony/symfony/blob/2.7/UPGRADE-2.7.md#Form 

> In form types and extension overriding the "setDefaultOptions" of the AbstractType or AbstractExtensionType has been deprecated in favor of overriding the new "configureOptions" method.

### CODE REVIEW

**Comment by bojanz** [comment]
Good catch! Can you please rebase to remove the merge commit?

**Comment by dnagirl** [comment]
I thought I had rebased. I've been doing everything directly on github with no local copy so first I updated my fork to your master (which is what I understood rebasing to be) and then I edited `AddressType.php` and then I made the pull request.

Sorry I'm being thick but you are the lucky recipient ;) of my first pull requests. What step did I miss and could you point me at a tutorial?

**Comment by bojanz** [comment]
I think that the problem comes from the fact that your fork is not up to date with the origin.
So you've rebased, but it's still showing that one merge commit which is already in the latest master.

So you can either rebase against origin/master (if "origin" is your remote for this repo), or checkout master, pull origin, push to your fork, then rebase.

**Comment by dnagirl** [comment]
I've created a separate branch for this change.  Hopefully that will resolve the issue with the pull request.

**Pull request closed without merging**
