### PR TITLE
Re-order TW subdivisions to match official (post office) order

### PR DESCRIPTION
**Pull request by g-brodiei**
Alter the weight position of each county in TW.json, so it reflects the familiar position in Taiwan's county selection.

### CODE REVIEW

**Comment by bojanz** [comment]
You will want to open a bug report at https://github.com/googlei18n/libaddressinput/issues, our dataset is automatically generated from Google's endpoint. Once they make the change, it will be pulled into this library.

**Comment by g-brodiei** [comment]
Got it, thanks for the direction!

**Comment by bojanz** [comment]
The issue we're now tracking is https://github.com/google/libaddressinput/issues/204

**Comment by bojanz** [comment]
@g-brodiei 
We have now opened addressing 2.x, and no longer require changes to first appear in Google's address formats, since they've been too slow to update (as is obvious here).

So, I would like to proceed with updating the order of the TW subdivisions. However, in this MR the order is not the same as in https://github.com/google/libaddressinput/issues/204 (and the TW post dropdown). Is that intentional, or accidental?

**Comment by g-brodiei** [comment]
Hi @bojanz,
Sorry, that change was an accidental difference. 
We should still follow the order given in  google/libaddressinput#204 (and the TW post official site).
I'll make the change with a new commit thanks for attending to detail

**Comment by g-brodiei** [comment]
The commit is now updated and follows the order given by the TW post official site, which is in geographical order.  

image

**Comment by bojanz** [comment]
@g-brodiei 
Thank you for the fast update, and for your persistence, greatly appreciated.

**Pull request merged**
