### PR TITLE
Fix subdivision name generation for countries with translations (e.g. Canada)

### PR DESCRIPTION
**Pull request by dww**
As per IRC discussion with bojanz, the current version of this library doesn't include the English versions of Canadian provinces.  This PR has 2 commits, one with fixes to generate.php, and one with the updated CA.json as a result of running the new version.  CA.json is the only data file that's changed with the new logic in generate.php.

### CODE REVIEW

**Comment by dww** [comment]
Bah, this isn't right, either.  I've now enabled various languages on my site, and I can't get the French versions to appear at all.  Upon a quick glance, there appears to be nothing locale-aware about subdivisions at all.  While the country list is getting localized, subdivisions aren't.  For example, if I enable zh-hans, the country list is in Chinese, but when I select '中国' as the country (CN), the values for the province drop down are still the English names (e.g. 'Macau', 'Beijing Shi') not the locale-aware values.  So I think there's a deeper bug (in address.module?), that means we never ask the SubdivisionRepository for locale-appropriate values.  Until that's straightened out, you might want to hold off merging this, since I fear this isn't ideal.  If I hard-code the locale to be fr within the SubdivisionRepository, this version of CA.json throws errors because it assumes local_name will exist.

**Comment by dww** [comment]
Okay, I looked more closely into this.  Once I got some address.module locale-related bugs sorted out (I'll post a d.o issue about those), I was finally able to see locale-specific subdivisions working properly for other countries.  Then, I was able to better understand the desired source data for CA.json.  I had made some wrong assumptions just reading the generate.php code.  But seeing it in action revealed that we always need to define local_name and local_code if we're going to be trying to support locale, even if they duplicate 'name' and/or the code we're indexing by.  The previous code in here wasn't handling that right, but I pushed 2 new commits that do:

commit 79c2f784bf -- fix to generate.php
commit 442feedd97 -- fix to CA.json

These are hereby ready for a merge.

Thanks,
-Derek

**Comment by bojanz** [comment]
https://github.com/commerceguys/addressing/blob/master/src/Subdivision/SubdivisionRepository.php#L186 might be of interest, this is how we are allowed to strip duplicate properties.

**Comment by dww** [comment]
Thanks for the pointer.  Indeed, that's of interest.  And it confirms my latest fixes.  We need to have a local_code, even if it matches the index key we're using.  In the case of CA.json, we want a separate local_name vs. local_code, since CA uses 2 letter codes, not the full province names.

**Comment by bojanz** [comment]
Thanks @dww, that was the right approach. Tweaked a bit and committed in 3c91c27c74c32b11e17e8cebc2a4badaa0b7cedc

**Pull request closed without merging**
