### PR TITLE
Chilean provinces update (Ñuble Province)

### PR DESCRIPTION
**Pull request by pgnjidic**
From 2018, there is a province named Ñuble, which is no longer part of the Biobio province, however, this name is not an option to select by the customer when writing the billing and shipping information on the website.

This may cause some confusion when delivering orders to customers in that area, as they cannot write their addresses the proper way.

### CODE REVIEW

**Comment by bojanz** [comment]
Fixed in 11aac9e5095226b652b910ea82c7c857ab30eebd.

**Comment by mnico** [comment]
> Fixed in [11aac9e](https://github.com/commerceguys/addressing/commit/11aac9e5095226b652b910ea82c7c857ab30eebd).

Hello thank you very much!

What can we do to update the Biobio [subdivisions](https://github.com/commerceguys/addressing/blob/master/resources/subdivision/CL-25f59066b2192db7c4158d743587052f.json) and add the Ñuble subdivisions? Some subdivisions of Biobio go to Ñuble for example.

This pull request tried to do that ;)

Regards

**Comment by bojanz** [comment]
The data in resources/ is auto-generated and can't be modified. You need to open an issue on https://github.com/google/libaddressinput/issues, proposing your changes, and when they make the changes, they will be pulled down automatically into this project.

**Comment by bojanz** [comment]
Committed the rest of this PR, now that we no longer auto-generate the subdivision data.

Commit: 16d74079eaf3434f1a013886941403936cf1f520

Sorry for not doing this sooner.

**Pull request closed without merging**
