### PR TITLE
Add subdivision for Paraguay

### PR DESCRIPTION
**Pull request by jaranetwork**

### CODE REVIEW

**Comment by bojanz** [comment]
Please open an issue at https://github.com/google/libaddressinput/issues requesting this change. Once it is added upstream, it will be automatically pulled into this library.

**Comment by bojanz** [comment]
We no longer need to wait for Google (we've disconnected from their formats), so we can proceed with this.

Looks like we need to set the administrative_area_type to "department". The field is optional (as already done in the MR).

Question: Should the format be "%postalCode %locality, %administrativeArea" (with a comma) as shown on https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/pryEn.pdf

**Comment by jaranetwork** [comment]
It can also be used separated with a comma as shown in UPU just like Uruguay uses department.

**Comment by bojanz** [comment]
Committed in a10be69de4aaad6b096d6123e3d5a70d63793897, thanks!

**Pull request closed without merging**
