### PR TITLE
Fix bug when formatting an address with multibyte (Japanese) characters

### PR DESCRIPTION
**Pull request by felixmaier1989**
I ran through some issues when dealing with concatenated Japanese chars.

### CODE REVIEW

**Comment by bojanz** [comment]
Sorry for looking at this so late.

I added your test without the fix, and it still passed.
We need to get a test failing before we commit a fix (I was wondering if adding /u to the preg_replace would be better than using eregi, but can't prove it without a test).

**Comment by felixmaier1989** [comment]
I guess this might be related to the PHP configuration.

What encodings have you set locally?
```php
echo mb_internal_encoding(); // For me: UTF-8
echo mb_regex_encoding(); // For me: UTF-8
```

Or would you have other ideas what would the difference between your system and mine?

**Comment by bojanz** [comment]
Push a commit that reverts the fix while keeping the test, let's see what happens on Travis.

**Comment by bojanz** [comment]
The test only PR (#81) passed on Travis. So we need a different test.

**Comment by bojanz** [comment]
We have never managed to reproduce this with a failing test, so closing PR as outdated.

**Pull request closed without merging**
