### PR TITLE
Correct suffixes for urkrainian region names

### PR DESCRIPTION
**Pull request by vladdancer**
Update region name to use the same suffix pattern.

### CODE REVIEW

**Comment by bojanz** [comment]
Hi, please revert the changes to SubdivisionUpdater, its purpose is to convert existing data in old (pre-2.x) installs, so it needs to have the old names.

**Comment by vladdancer** [comment]
@bojanz , fixed.

**Comment by bojanz** [comment]
@vladdancer 
Thanks! I've pushed a followup commit here that brings us in sync with ISO:
https://github.com/commerceguys/addressing/commit/3e679cd280169109ab6f9d7bff0d069e14d309ac

**Comment by vladdancer** [comment]
@bojanz , thanks! I'm not familiar with ISO standards but looks good to me.

**Pull request merged**
